/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author carra
 */
public class conversor extends javax.swing.JFrame {

    /**
     * Creates new form conversor
     */
    public conversor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jspnCantidadMonedas = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jlblCantidadConvertida = new javax.swing.JLabel();
        jcbxMonedaAConvertir = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jbtnConfirmar = new javax.swing.JButton();
        jcbxMonedaActual = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jbtnReiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Conversor de Monedas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Variable", 1, 24), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jspnCantidadMonedas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 200, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cantidad Convertida");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 320, 50));

        jlblCantidadConvertida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlblCantidadConvertida.setForeground(new java.awt.Color(204, 0, 0));
        jlblCantidadConvertida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCantidadConvertida.setText("S/. 0.00");
        jPanel1.add(jlblCantidadConvertida, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 320, 50));

        jcbxMonedaAConvertir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD $ - Dólar estadounidense", "EUR € - Euro", "JPY ¥ - Yen japonés", "GBP £ - Libra esterlina", "CNY ¥ - Yuan chino", "MXN $ - Peso mexicano" }));
        jPanel1.add(jcbxMonedaAConvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 140, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cantidad a Convertir");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 320, 40));

        jbtnConfirmar.setBackground(new java.awt.Color(0, 153, 0));
        jbtnConfirmar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnConfirmar.setText("Confirmar");
        jPanel1.add(jbtnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 140, 50));

        jcbxMonedaActual.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PEN S/. - Nuevo sol peruano" }));
        jPanel1.add(jcbxMonedaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 140, 40));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("A");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 50, 40));

        jbtnReiniciar.setBackground(new java.awt.Color(0, 102, 204));
        jbtnReiniciar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnReiniciar.setText("Reiniciar");
        jPanel1.add(jbtnReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 140, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new conversor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton jbtnConfirmar;
    public javax.swing.JButton jbtnReiniciar;
    public javax.swing.JComboBox<String> jcbxMonedaAConvertir;
    public javax.swing.JComboBox<String> jcbxMonedaActual;
    public javax.swing.JLabel jlblCantidadConvertida;
    public javax.swing.JSpinner jspnCantidadMonedas;
    // End of variables declaration//GEN-END:variables
}
